### ISSUE TITLE
Error when opening chat history: arm64 <> x86_64 incompatibility

### ISSUE THREAD

**Issue by ghost** [zeitlings/ayai-gpt-nexus#1]
Hi, amazing job on this workflow!

I'm getting the following error when I try to open the chat history:

`Code 127: ~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/6573F0DC-08DA-4B1B-90E1-72E7DB56ABF1:7: bad CPU type in executable: ./src/Archive`

While we're on the topic, would it be possible to make the chat history optional, as in the "official" Alfred ChatGPT workflow?

**Comment by zeitlings** [comment]
> bad CPU type in executable

Haven't seen that one before, but I'm somewhat sure it's because I admitteldy haphazardly compiled "Archive.swift" with `swiftc` on an ARM Mac while yours is most likely Intel. Just delete the existing binary and compile the script again: `swiftc -O Archive.swift`. Alternatively you can delete the binary and uncomment the first two lines in the "Chat History" Script Filter object and comment out all others. Make sure you have the Xcode Command Line Tools installed or `swiftc` won't be available: `xcode-select --install`.

> While we're on the topic, would it be possible to make the chat history optional, as in the "official" Alfred ChatGPT workflow?

Sure, I'll add it to the next update.

**Comment by zeitlings** [comment]
@glowacky `alpha.3` now bundles a universal binary. Let me know if this works for you, in which case you can also ignore the above instructions!

**Comment by ghost** [comment]
@zeitlings New version works great, thanks! 🙏
