### ISSUE TITLE
Claude: Unable to send queries (first message must use the "user" role)

### ISSUE THREAD

**Issue by lcpichette** [zeitlings/ayai-gpt-nexus#3]
Claude error:

􀇾 messages: first message must use the "user" role

![2024-07-15@23 55 57 July-15@2x](https://github.com/user-attachments/assets/968caef9-a8dc-49d3-a517-3fa73e1100bd)

ChatGPT works

![2024-07-15@23 13 58 July-15@2x](https://github.com/user-attachments/assets/e79d1e51-51f7-4afc-99ce-76c094d096b8)

This has been an incredible tool for me, and it's an impressive stage for just being in alpha. Thank you to all of the contributors.

**Comment by zeitlings** [comment]
Hey @lcpichette 
Can you give me some more context? E.g., what the workflow version is, some info about the configuration you've set up, what the steps are before the error occurs (I can not reproduce it) and whatever else you think might be helpful. Did you inspect the actual `chat.json`? You can find it in the workflow's cache folder, or, after starting a new chat, in the archive (View the history and hit <kbd>⌘</kbd><kbd>↩</kbd> on the chat to reveal it in Finder). What is there other than a user message? Did you start the conversation with ChatGPT and tried to continue with Claude? (Perhaps some function call metadata is confusing Claude?)

And by the by, some icons are not rendering for you. To see them, you can just install Apple's [SF Pro](https://developer.apple.com/fonts/) font. 

> This has been an incredible tool for me, and it's an impressive stage for just being in alpha. Thank you to all of the contributors.

Thanks for the kind words!

**Comment by lcpichette** [comment]
# v1.0.0 v4
![2024-07-16@08 42 08 July-16@2x](https://github.com/user-attachments/assets/b7d6a4a6-3396-4c38-9f0f-e3fe4b44ac63)

![2024-07-16@08 32 08 July-16@2x](https://github.com/user-attachments/assets/05c98984-b5bd-4238-a6be-10e2664b3b3c)

I don't believe I've made any other tweaks -- I'm not sure how I would. I'm pretty new to Alfred. 

Cmd+enter (with prefix c, my "ask" keyword, or not) don't seem to reveal the archive in finder. Maybe I'm doing this incorrectly, or misunderstanding?

If you look at the bottom of the Alfred window in the below video you'll see the text changing, and that's me attempting to press cmd+return

https://github.com/user-attachments/assets/e671def5-baa7-4a74-ba50-b830256512c8

**Comment by zeitlings** [comment]
Hey @lcpichette 
Did you try just starting a new chat with <kbd>⌘</kbd><kbd>↩</kbd> while viewing the chat window?


<img src="https://github.com/user-attachments/assets/3d5fa766-b2a9-4a8c-9137-267226b31172" width="550px" style="max-width: 100%;">

You can access the chat history via `ask` or `c` in your case, and then hitting <kbd>⌥</kbd><kbd>↩</kbd>. Here you would press <kbd>⌘</kbd><kbd>↩</kbd> on the archived chat you want to reveal in the Finder.

<img src="/zeitlings/ayai-gpt-nexus/raw/main/assets/images/preview/keyword.png" width="550px" style="max-width: 100%;">

<img src="https://github.com/user-attachments/assets/a20f6eb3-890d-4864-b595-3c6dbb96c7e3" width="550px" style="max-width: 100%;">


(Another side note: I'd recommend using the newer [Claude 3.5 Sonnet](https://www.anthropic.com/news/claude-3-5-sonnet) over Opus since it is cheaper and more capable.)

**Comment by lcpichette** [comment]
Thank you for the quick replies -- I'll switch over to 3.5 Sonnet right after I send this.

In the first video you'll see it not working while I attempt `⌘↩ while viewing the chat window`

https://github.com/user-attachments/assets/6feb7c64-bd30-424d-bd28-f1b1e8422d90

In this second window you'll see me attempt to perform `⌥↩. Here you would press ⌘↩ on the archived chat`. 

https://github.com/user-attachments/assets/d6c4a166-cdf7-4ea0-b4e8-8505e86fbb7b

It seems that you're able to use Claude just fine -- so I'm not sure what the issue is. My key appears to be correct, and I'd think it'd give me a different error if that was the issue. Again, I appreciate you looking into this : )

**Comment by zeitlings** [comment]
Hey, thanks for the videos. Your second example shows us that you've never actually started a new chat, which should happen when pressing <kbd>↩</kbd> while holding <kbd>⌘</kbd> on the chat window (or when you type the keyword `ask`, or `c` in your case). When creating a new chat, the old conversation gets moved to the archive. At this point it would be visible in the chat history. Given that the message says that no previous chats were archived, this never happened.

Trying to judge from the first video, it's difficult to tell if you're actually still holding <kbd>⌘</kbd> before hitting return. If you let go of it before pressing enter, you are just sending another message to the same conversation. 

There's currently no direct way to inspect the workflow's cache folder directly. If you know how to retrieve it via Alfred's environment variables, I'd ask you to do so, open it and check the chat.json there. 

Otherwise, you can open it via tools like this workflow: https://github.com/twio142/alfred-workflows. Using this workflow, pressing <kbd>⌃</kbd><kbd>↵</kbd> on the Ayai workflow will open its cache folder. Another approach would be to just uninstall GPT Nexus (hope that Alfred cleans up the cache folder), reinstall it and check if the problem occurs again.

**Comment by lcpichette** [comment]
I'm not sure what you mean, I've sent chats to chatgpt and claude before. Maybe I'm misunderstanding.

**Comment by zeitlings** [comment]
Hmm, let's try that again then and start by clarifying a few points to resolve the issue:

1. **Starting a New Chat**:
    - To start a new chat, hold down the `⌘` key and then press `↩` while viewing the chat window. This archives the current chat and starts a new one.
    - If you see the text changing at the bottom of the Alfred window while attempting this, make sure you are holding `⌘` the entire time before pressing `↩`.

2. **Accessing Chat Archive**:
    - To access the chat history, type your keyword (`ask` or `c`) and press `⌥↩`. This will display archived chats.
    - Then, press `⌘↩` on the chat you want to reveal in Finder.
    - **Important**: If no chats are visible in the chat history, it means no new chat was created. In this case, please ensure you follow step 1 correctly. 


3. **Cache Folder Inspection**:
    - Use this [Alfred workflow](https://github.com/twio142/alfred-workflows) to access the cache folder. Install it, and then press `⌃↵` on the Ayai workflow to open its cache folder.
    - Alternatively, uninstall and reinstall GPT Nexus to clear potential cache issues.

4. **Understanding the Error**:
    - The error `messages: first message must use the "user" role` suggests the chat didn't start correctly. Follow the steps to start a new chat properly.

If you are absolutely sure you did step 1 correctly and the issue persists, the problem might lie elsewhere. In that case, please open the Alfred debugger by pressing `⌘D` and check for any additional error messages that might provide more insight.

Please try these steps and let me know if the issue persists. If possible, share another video showing the complete process of starting a new chat and accessing the archive.
