### ISSUE TITLE
Ability to choose service dynamically

### ISSUE THREAD

**Issue by myhau** [zeitlings/ayai-gpt-nexus#5]
First of all, Ayai is a really nice Alfred Workflow! I'm using it every day :).

It would be very nice to have an ability to change model dynamically (e.g. by defining custom keywords). For example, while I would like the default model to be Claude Sonnet 3.5, from time to time I want to use Perplexity Online model. It could be solved by having two (or more) keywords: `ask` (default) and `ask-perplexity`.

**Comment by zeitlings** [comment]
Hey @myhau 

Happy to hear you find it useful! You already do have the ability to change the service with the method you propose.
All you have to do is to copy the Keyword object (`ask`), set the `primary_endpoint` variable to `Perplexity` via the [Args and Vars Utility](https://www.alfredapp.com/help/workflows/utilities/argument/) and connect it with at least the nodes that continue the chat and start a new one. 

Here is a working demo as an external extension that makes use of [external triggers](https://www.alfredapp.com/help/workflows/outputs/call-external-trigger/):
- [Ayai · GPT Nexus Extension [Demo]](https://transfer.archivete.am/l6MUi/Ayai%20%C2%B7%20GPT%20Nexus%20Extension%20%5BDemo%5D.alfredworkflow) workflow.

If you want to change the model instead of the service, you can set the correlating variable in the same way. I have written some more information in the "About" section of the workflow to get you started.
